# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

about-check-updates = Rechercher des mises à jour
about-copy = Copier dans le presse-papiers
about-system =
    CPU : { $cpu }
    Mémoire : { $memoryMb } Mo
    Version OS : { $osVersion }
    Distributeur de cartes graphiques : { $graphicsCardVendor }
    Carte graphique : { $graphicsCard }
about-tab-credits = Remerciements
about-tab-info = Infos
about-tab-licences = Licences
about-title = À PROPOS DE { $capitalizedAppName }
