# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

debug-reset = Paramètres par défaut
debug-title = PARAMÈTRES DE DÉBOGAGE
menu-debug = Débogage
menu-show-debug = Afficher le menu de débogage
menu-show-debug-settings = Afficher les paramètres de débogage
