# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

login-create-account = S'inscrire
login-grid = Grille
login-log-in = Connexion
login-need-help = Mot de passe oublié
login-password = Mot de passe
login-remember-password = Mémoriser le mot de passe
login-remember-username = Se souvenir de moi
login-start-home = Domicile
login-start-last-location = Dernier emplacement
login-username = Nom d'utilisateur
menu-about = À propos de { $appName }
menu-community-forums = Forums de la communauté
menu-exit = Quitter { $appName }
menu-guidebook = Aide rapide...
menu-help = Aide
menu-knowledge-base = Base de connaissances
menu-me = Moi
menu-preferences = Préférences...
menu-support = Portail d'assistance
menu-wiki = Wiki
