# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

about-check-updates = Buscar actualizaciones
about-copy = Copiar al portapapeles
about-system =
    CPU: { $cpu }
    Memoria: { $memoryMb } MB
    Versión del Sistema Operativo: { $osVersion }
    Fabricante de la tarjeta gráfica: { $graphicsCardVendor }
    Tarjeta gráfica: { $graphicsCard }
about-tab-credits = Créditos
about-tab-info = Información
about-tab-licences = Licencias
about-title = ACERCA DE { $capitalizedAppName }
