# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

debug-reset = Volver a las opciones por defecto
debug-title = CONFIGURACIONES DEL DEPURADOR
menu-debug = Depurar
menu-show-debug = Mostrar el menú 'Debug'
menu-show-debug-settings = Mostrar las configuraciones del depurador
