# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

login-create-account = Regístrate
login-grid = Red
login-log-in = Iniciar sesión
login-need-help = Contraseña olvidada
login-password = Contraseña
login-remember-password = Recordar contraseña
login-remember-username = Recordarme
login-start-home = Mi Base
login-start-last-location = Mi última posición
login-username = Nombre de usuario
menu-about = Acerca de { $appName }
menu-community-forums = Foros comunitarios
menu-exit = Salir de { $appName }
menu-guidebook = Cómo...
menu-help = Ayuda
menu-knowledge-base = Base de Conocimientos
menu-me = Yo
menu-preferences = Preferencias...
menu-support = Portal de soporte
menu-wiki = Wiki
