# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

about-check-updates = Cerca aggiornamenti
about-copy = Copia negli appunti
about-system =
    CPU: { $cpu }
    Memoria: { $memoryMb } MB
    Versione sistema operativo: { $osVersion }
    Venditore scheda grafica: { $graphicsCardVendor }
    Scheda grafica: { $graphicsCard }
about-tab-credits = Ringraziamenti
about-tab-info = Informazioni
about-tab-licences = Licenze
about-title = INFO { $capitalizedAppName }
