# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

debug-reset = Reimposta i valori di default
debug-title = PARAMETRI DI DEBUG
menu-debug = Debug
menu-show-debug = Mostra menu Debug
menu-show-debug-settings = Mostra impostazioni di debug
