# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

login-create-account = Registrati
login-grid = Grid
login-log-in = Accedi
login-need-help = Password dimenticata
login-password = Password
login-remember-password = Ricorda la password
login-remember-username = Ricordati di me
login-start-home = Casa mia
login-start-last-location = La mia ultima ubicazione
login-username = Nome utente
menu-about = Informazioni su { $appName }
menu-community-forums = Forum della comunità
menu-exit = Esci da { $appName }
menu-guidebook = Istruzioni...
menu-help = Aiuto
menu-knowledge-base = Base di conoscenza
menu-me = Io
menu-preferences = Preferenze...
menu-support = Portale assistenza
menu-wiki = Wiki
