# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

about-check-updates = Güncellemeleri kontrol et
about-copy = Panoya Kopyala
about-system =
    CPU: { $cpu }
    Bellek: { $memoryMb } MB
    İşl. Sis. Sürümü: { $osVersion }
    Grafik Kartı Üreticisi: { $graphicsCardVendor }
    Grafik Kartı: { $graphicsCard }
about-tab-credits = Katkıda Bulunanlar
about-tab-info = Bilgi
about-tab-licences = Lisanslar
about-title = { $capitalizedAppName } HAKKINDA
