# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

debug-reset = Varsayılana sıfırla
debug-title = HATA AYIKLAMA AYARLARI
menu-debug = Hata ayıkla
menu-show-debug = Hata Ayıklama Menüsünü Göster
menu-show-debug-settings = Hata Ayıklama Ayarlarını Göster
