# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

login-create-account = Kaydol
login-grid = Ağ
login-log-in = Oturum Aç
login-need-help = Parolamı unuttum
login-password = Parola
login-start-home = Ana konumum
login-start-last-location = Son konumum
login-username = Kullanıcı Adı
menu-about = { $appName } Hakkında
menu-community-forums = Topluluk Forumları
menu-exit = { $appName }'den Çık
menu-guidebook = Nasıl yapılır...
menu-help = Yardım
menu-knowledge-base = Bilgi Bankası
menu-me = Ben
menu-preferences = Tercihler...
menu-support = Destek porteli
menu-wiki = Wiki
