# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

about-check-updates = Проверить наличие обновлений
about-copy = Копировать в буфер обмена
about-system =
    ЦП: { $cpu }
    Память: { $memoryMb } МБ
    Версия ОС: { $osVersion }
    Производитель графической платы: { $graphicsCardVendor }
    Графическая плата: { $graphicsCard }
about-tab-credits = Создатели
about-tab-info = Данные
about-tab-licences = Лицензии
about-title = О { $capitalizedAppName }
