# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

debug-reset = Сброс в стандартное значение
debug-title = НАСТРОЙКИ ОТЛАДКИ
menu-debug = Отладка
menu-show-debug = Показать меню отладки
menu-show-debug-settings = Настройки отладки
