# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

login-create-account = Регистрация
login-grid = Сетка
login-log-in = Войти
login-need-help = Забыли пароль?
login-password = Пароль
login-start-home = Мой дом
login-start-last-location = Последнее местоположение
login-username = Имя пользователя
menu-about = О { $appName }
menu-community-forums = Форумы сообщества
menu-exit = Выход из { $appName }
menu-guidebook = Инструкции...
menu-help = Справка
menu-knowledge-base = База знаний
menu-me = Я
menu-preferences = Настройки...
menu-support = Портал поддержки
menu-wiki = Wiki
