# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

about-copy = Kopiér til udklipsholder
about-tab-credits = Tak til
about-tab-info = Info
about-tab-licences = Licenser
about-title = OM { $capitalizedAppName }
