# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

debug-reset = Sæt til standard
debug-title = DEBUG INDSTILLINGER
menu-debug = Debug
menu-show-debug = Vis debug menu
menu-show-debug-settings = Vis debug opsætning
