# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

login-grid = Grid
login-log-in = Log på
login-need-help = Har du glemt brugernavn eller password?
login-start-home = Hjem
login-start-last-location = Min sidste lokation
menu-about = Om { $appName }
menu-exit = Afslut { $appName }
menu-help = Hjælp
menu-me = Mig
menu-preferences = Indstillinger
