# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

about-check-updates = Nach Updates suchen
about-copy = In Zwischenablage kopieren
about-system =
    CPU: { $cpu }
    Speicher: { $memoryMb } MB
    Betriebssystemversion: { $osVersion }
    Grafikkartenhersteller: { $graphicsCardVendor }
    Grafikkarte: { $graphicsCard }
about-tab-credits = Danksagung
about-tab-info = Info
about-tab-licences = Lizenzen
about-title = INFO ÜBER { $capitalizedAppName }
