# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

debug-reset = Standard wiederherstellen
debug-title = DEBUG-EINSTELLUNGEN
menu-debug = Debug
menu-show-debug = Debug-Menü anzeigen
menu-show-debug-settings = Debug-Einstellungen anzeigen
