# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

login-create-account = Registrieren
login-grid = Raster
login-log-in = Anmelden
login-need-help = Kennwort vergessen
login-password = Kennwort
login-remember-password = Kennwort speichern
login-remember-username = An mich erinnern
login-start-home = Mein Zuhause
login-start-last-location = Mein letzter Standort
login-username = Benutzername
menu-about = INFO ÜBER { $appName }
menu-community-forums = Community-Foren
menu-exit = { $appName } schließen
menu-guidebook = Anweisungen...
menu-help = Hilfe
menu-knowledge-base = Knowledge Base
menu-me = Ich
menu-preferences = Einstellungen...
menu-support = Support-Portal
menu-wiki = Wiki
