# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

about-check-updates = 查詢是否有更新版
about-copy = 覆製到剪貼簿
about-system =
    CPU：{ $cpu }
    記憶體：{ $memoryMb } MB
    作業系統版本：{ $osVersion }
    顯示卡供應商：{ $graphicsCardVendor }
    顯示卡：{ $graphicsCard }
about-tab-credits = 貸記
about-tab-info = 資訊
about-tab-licences = 許可
about-title = 關於 { $capitalizedAppName }
