# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

debug-reset = 回復至預設值
debug-title = 除錯設定
menu-debug = 除錯
menu-show-debug = 顯示除錯選單
menu-show-debug-settings = 顯示除錯設定
