# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

login-create-account = 註冊
login-grid = 網格
login-log-in = 登入
login-need-help = 忘記密碼
login-password = 密碼
login-start-home = 我的家
login-start-last-location = 我上一次位置
login-username = 使用者名稱
menu-about = 關於 { $appName }
menu-community-forums = 社群論壇
menu-exit = 退出 { $appName }
menu-guidebook = 簡易教學…
menu-help = 幫助
menu-knowledge-base = 知識庫
menu-me = 我自己
menu-preferences = 偏好設定…
menu-support = 支援入口
menu-wiki = 維基
