# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

about-check-updates = Verificar atualizações
about-copy = Copiar
about-system =
    CPU: { $cpu }
    Memória: { $memoryMb } MBs
    Versão OS: { $osVersion }
    Placa de vídeo: { $graphicsCardVendor }
    Placa gráfica: { $graphicsCard }
about-tab-credits = Créditos
about-tab-info = Info
about-tab-licences = Licenças
about-title = SOBRE { $capitalizedAppName }
