# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

debug-reset = Restaurar padrão
debug-title = DEBUG SETTINGS
menu-debug = Depurar
menu-show-debug = Exibir menu de depuração
menu-show-debug-settings = Mostrar configurações
