# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

login-create-account = Cadastre-se
login-grid = Grade
login-log-in = Login
login-need-help = Senha esquecida
login-password = Senha
login-remember-password = Lembrar Senha
login-remember-username = Lembrar de mim
login-start-home = Minha casa
login-start-last-location = Última posição
login-username = Nome de usuário
menu-about = Sobre { $appName }
menu-community-forums = Fóruns da comunidade
menu-exit = Sair do { $appName }
menu-guidebook = Como...
menu-help = Ajuda
menu-knowledge-base = Base de conhecimento
menu-me = Eu
menu-preferences = Preferências...
menu-support = Portal de suporte
menu-wiki = Wiki
