# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

about-check-updates = 更新を確認
about-copy = 情報をコピー
about-system =
    ＣＰＵ：{ $cpu }
    メモリ：{ $memoryMb }㎆
    ＯＳのバージョン：{ $osVersion }
    グラフィックカード製造元：{ $graphicsCardVendor }
    グラフィックカード:{ $graphicsCard }
about-tab-credits = クレジット
about-tab-info = 情報
about-tab-licences = ライセンス
about-title = { $capitalizedAppName }について
