# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

debug-changed-only = 変更された設定のみ表示
debug-reset = デフォルトにリセット
debug-search = 検索語句を入力
debug-title = デバッグ設定
menu-debug = デバッグ
menu-show-debug = デバッグメニューを表示する
menu-show-debug-settings = デバッグ設定を表示
