# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

login-create-account = サインアップ
login-grid = グリッド
login-log-in = ログイン
login-need-help = パスワードヘルプ
login-password = パスワード
login-remember-password = パスワード再発行
login-remember-username = パスワードを記録
login-start-home = ホーム
login-start-last-location = 最後にいた場所
login-username = ユーザ名
menu-about = { $appName }について
menu-community-forums = Second Lifeコミュニティフォーラム
menu-exit = { $appName }を終了
menu-guidebook = ハウツー…
menu-help = ヘルプ
menu-knowledge-base = Second Lifeナレッジベース
menu-me = 私
menu-preferences = 初期設定…
menu-support = Second Lifeサポートポータル
menu-wiki = Second Life Wiki
