# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

about-copy = Kopiuj do schowka
about-system =
    Procesor (CPU): { $cpu }
    Pamięć (Memory): { $memoryMb } MB
    System operacyjny (OS Version): { $osVersion }
    Dostawca karty graficznej (Graphics Card Vendor): { $graphicsCardVendor }
    Karta graficzna (Graphics Card): { $graphicsCard }
about-tab-credits = Podziękowania
about-tab-info = Informacje
about-tab-licences = Licencje
about-title = O { $capitalizedAppName }
