# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

debug-reset = Domyślnie
debug-title = USTAWIENIA DEBUGOWANIA
menu-debug = Debugowanie
menu-show-debug = Pokaż menu debugowania
menu-show-debug-settings = Pokaż ustawienia debugowania
