# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

login-log-in = Zaloguj
login-need-help = Zapomniałem/am hasła
login-password = Hasło
login-start-home = Moje miejsce startu
login-start-last-location = Ostatnia lokalizacja
login-username = Użytkownik
menu-about = Informacje o { $appName }
menu-community-forums = Forum społecznościowe
menu-exit = Wyłącz { $appName }
menu-guidebook = Samouczek...
menu-help = Pomoc
menu-knowledge-base = Baza wiedzy
menu-me = Ja
menu-preferences = Preferencje...
menu-support = Portal wsparcia
menu-wiki = Wiki informacyjna
