# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

about-check-updates = Check for Updates
about-copy = Copy Info
about-system =
    CPU: { $cpu }
    Memory: { $memoryMb } MB
    Concurrency: { $concurrency }
    OS Version: { $osVersion }
    Graphics Card Vendor: { $graphicsCardVendor }
    Graphics Card: { $graphicsCard }
about-tab-credits = CREDITS
about-tab-info = INFO
about-tab-licences = LICENCES
about-title = ABOUT { $capitalizedAppName }
