# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

debug-changed-only = Show changed settings only
debug-reset = Reset to default
debug-search = Enter search text
debug-title = DEBUG SETTINGS
menu-debug = Debug
menu-show-debug = Show Debug Menu
menu-show-debug-settings = Show Debug Settings
