# Generated by `cargo run --features harvest --bin harvest`.
# Source: indra/newview/skins/default/xui/<locale>/. Do not edit by hand.

login-create-account = Create account
login-grid = Grid
login-log-in = Log in
login-need-help = Need help logging in?
login-password = Password
login-remember-password = Remember password
login-remember-username = Remember username
login-start-here = Start here
login-start-home = My home
login-start-last-location = My last location
login-username = Username
menu-about = About { $appName }
menu-community-forums = Community Forums
menu-exit = Exit { $appName }
menu-guidebook = Guidebook
menu-help = Help
menu-knowledge-base = Knowledge Base
menu-me = Me
menu-preferences = Preferences...
menu-support = Support portal
menu-wiki = Wiki
